version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.17.0
    commands:
      - npm install -g typescript
  pre_build:
    commands:
      - echo Install packages...
      - npm install
  build:
    commands:
      - echo Create build...
      - npm run build
      - npm prune --production
  post_build:
    commands:
      - echo Removing unnecessary files...
artifacts:
  files:
    - dist/**/*
    - package.json
    - package-lock.json
    - node_modules/**/*
