phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started...
      - npm run build
  post_build:
    commands:
      - echo removing unnecessary files ...
      - rm -rf node_modules/
artifacts:
  base-directory: '.'
  files:
    - '**/*'
