version: "3"
services:
  server:
    environment:
      PORT: ${PORT}
      MONGO_URL: ${MONGO_URL}
      JWT_SECRET: ${JWT_SECRET}
      STAGE: ${STAGE}
      IMAGE_NAME: ${IMAGE_NAME}
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    image: ${IMAGE_NAME}
    ports:
      - ${PORT}:${PORT}
