version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${STAGE}
    image: ${IMAGE_NAME}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - /app/node_modules
