apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan
spec:
  selector:
    matchLabels:
      run: loan
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: loan
    spec:
      containers:
      - name: loan
        image: 078748998279.dkr.ecr.us-east-1.amazonaws.com/loan:v1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: "hola mundo cruel"
      imagePullSecrets:
      - name: registrykey


---

apiVersion: v1
kind: Service
metadata:
  name: loan
  labels:
    run: loan
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8080
  selector:
    run: loan