name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Docker login
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD }}
      run:
        echo "Start login"
        docker login -u $DOCKER_USER -p DOCKER_PASSWORD
        echo "End login"
    - name: Buid image
      env:
        PORT: 8080
        MONGO_URL: ${{ MONGO_URL }}
        JWT_SECRET: ${{ JWT_SECRET }}
        STAGE: prod
        IMAGE_NAME: carloscb8080/loan:v1.0.0
      run:
        docker compose -f docker-compose.prod.yml build
    - name: Push image
      run:
        docker push carloscb8080/loan:v1.0.0
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
